# Generated by Django 5.0.6 on 2024-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
